name: Build and Publish Docker Images

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile.ubuntu'
      - '**.sh'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dockerfile: Dockerfile.ubuntu
            tag: docker-vicar/ubuntu
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@5
      with:
        context: .
        file: Dockerfile.ubuntu
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/${{ matrix.tag }}:latest
    - name: Run container and check
      run: |
        docker run --name test_container -d ${{ secrets.DOCKER_USERNAME }}/${{ matrix.tag }}:latest
        docker exec test_container /path/to/your/test/script.sh
        # Add commands here to inspect return code, check mounted volume, etc.
        # Ensure your script.sh inside the container can signal success/failure appropriately
